#!/usr/bin/env bash
# Must track xfg's file resolution (config/normalizer.ts, extends-resolver.ts) for names and createOnly.
# Usage: gen-xfg-managed-renovate.sh [dir] > .github/renovate/xfg-managed.json5
set -euo pipefail

config_dir="${1:-src}"

if [[ ! -d "$config_dir" ]]; then
  echo "xfg config directory not found: $config_dir" >&2
  exit 1
fi

# repo-operator keeps bumping its own copies: they are the source the sync sends out
readonly SELF_REPO="anthony-spruyt/repo-operator"

# shellcheck disable=SC2016
readonly JQ_MERGE='
{
  files: (map(.files // empty) | add // {}),
  groups: (map(.groups // empty) | add // {}),
  conditionalGroups: (map(.conditionalGroups // empty) | add // []),
  repos: (map(.repos // empty) | add // [])
}'

# shellcheck disable=SC2016
readonly JQ_RESOLVE='
def dedupe: reduce .[] as $x ([]; if any(.[]; . == $x) then . else . + [$x] end);
def as_list: if . == null then [] elif type == "array" then . else [.] end;

def chain($defs; $name; $seen):
  if any($seen[]; . == $name) then error("circular extends at group \($name)")
  elif ($defs | has($name) | not) then error("group \($name) does not exist")
  else [($defs[$name].extends | as_list)[] as $p | chain($defs; $p; $seen + [$name])[]] + [$name] | dedupe
  end;

def matches($when; $groups):
  ($when.allOf // null) as $all | ($when.anyOf // null) as $any | ($when.noneOf // null) as $none
  | ($all != null or $any != null or $none != null)
    and ($all == null or all($all[]; . as $g | any($groups[]; . == $g)))
    and ($any == null or any($any[]; . as $g | any($groups[]; . == $g)))
    and ($none == null or all($none[]; . as $g | all($groups[]; . != $g)));

def apply_layer($layer):
  (if $layer.inherit == false then {} else . end)
  | reduce ($layer | to_entries[] | select(.key != "inherit")) as $e (.;
      if $e.value == false then del(.[$e.key])
      elif $e.value == null then .
      elif has($e.key) then .[$e.key] += ($e.value | del(.override))
      else .[$e.key] = $e.value end);

def create_only($override; $base):
  if ($override | type) == "object" and $override.createOnly != null then $override.createOnly
  else $base.createOnly end;

def managed_files($cfg; $repo):
  ([($repo.groups // [])[] as $g | chain($cfg.groups; $g; [])[]] | dedupe) as $groups
  | (reduce $groups[] as $g ($cfg.files; apply_layer($cfg.groups[$g].files // {}))) as $grouped
  | (reduce ($cfg.conditionalGroups[] | select(matches(.when; $groups))) as $cg
      ($grouped; apply_layer($cg.files // {}))) as $root
  | ($repo.files // {}) as $own
  | ($own.inherit != false) as $inherit
  | [
      ($root | to_entries[]
        | select($own[.key] != false and ($inherit or $own[.key] != null))
        | select(create_only($own[.key]; .value) != true) | .key),
      ($own | to_entries[]
        | .key as $k | select($k != "inherit" and .value != false and ($root | has($k) | not))
        | select(create_only(.value; {}) != true) | .key)
    ]
  | sort;

def repo_name:
  if test("\\Ahttps://github\\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+\\z") then sub("^https://github\\.com/"; "") | sub("\\.git$"; "")
  else error("cannot turn git URL into a repo name: \(.)") end;

. as $cfg
| [ $cfg.repos[] as $repo | ($repo.git | as_list)[] | repo_name as $name
    | select($name != $self)
    | {name: $name, files: managed_files($cfg; $repo)} | select(.files | length > 0) ]
| (map(.files[]) | map(select(test("[*?\\[\\]{}()!+@]"))) | unique) as $globs
| if ($globs | length) > 0 then error("file names would be read as globs by matchFileNames: \($globs | join(", "))") else . end
| sort_by(.name)
| {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    packageRules: map({
      description: "xfg overwrites these files on every sync; repo-operator bumps them in src/ instead",
      matchRepositories: [.name],
      matchFileNames: .files,
      enabled: false
    })
  }'

fragments=()
while IFS= read -r -d '' file; do
  fragments+=("$file")
done < <(find "$config_dir" -mindepth 1 -name '.*' -prune -o -type f \( -iname '*.yaml' -o -iname '*.yml' \) -print0 | LC_ALL=C sort -z)

if [[ "${#fragments[@]}" -eq 0 ]]; then
  echo "no YAML files in $config_dir" >&2
  exit 1
fi

docs="$(for file in "${fragments[@]}"; do yq -o=json -I0 'explode(.)' "$file" || exit 1; done)"

# conditionalGroups apply in xfg's fragment load order, which this sort does not reproduce
if [[ "$(printf '%s\n' "$docs" | jq -s 'map(select(type == "object" and has("conditionalGroups"))) | length')" -gt 1 ]]; then
  echo "conditionalGroups must live in one config file" >&2
  exit 1
fi

preset="$(printf '%s\n' "$docs" | jq -s "$JQ_MERGE" | jq --arg self "$SELF_REPO" "$JQ_RESOLVE")"

echo "// Generated by .github/scripts/gen-xfg-managed-renovate.sh from src/ - do not edit"
printf '%s\n' "$preset"
