ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - DOCKERFILE_HADOLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY
  - SPELL_LYCHEE
  - YAML_YAMLLINT
EXCLUDED_DIRECTORIES:
  - .git
DEFAULT_BRANCH: main
IGNORE_GITIGNORED_FILES: true
