---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Trivy Filesystem Scan

on:
  workflow_call: {}

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: Scan Filesystem
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Trivy scan
        uses: $/.github/actions/trivy-scan
        with:
          scan-type: fs
          severity: CRITICAL,HIGH
          ignore-unfixed: "true"
          category: trivy-daily-repo
          trivyignores: .trivyignore.yaml
