---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: "SonarCloud"

on:
  pull_request:
    branches:
      - "main"

permissions: {}

concurrency:
  group: "sonarcloud-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  sonarcloud:
    name: "SonarCloud"
    permissions: {}
    uses: "./.github/workflows/_sonar-new-issues.yaml"
